name: CI — Todo App

on:
  push:
    branches: [main]

jobs:
  backend:
    name: Spring Boot
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
      - name: Compilation
        run: ./mvnw compile
      - name: Tests unitaires
        run: ./mvnw test
      - name: Build and test backend
        run: ./mvnw clean install

  frontend:
    name: Angular
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build and test frontend
        run: npm run build